# Numpy exercises for beginners

https://numpy.org/doc/stable/user/absolute_beginners.html
***

In [1]:
import numpy as np

In [3]:
a = np.arange(6)

In [4]:
a2 = a[np.newaxis, :]

In [10]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
a2.shape

(3, 4)

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])

In [13]:
a2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
print(a[0])

1


In [12]:
print(a2[2])

[ 9 10 11 12]


##### Adding, removing, and sorting elements

In [15]:
>>> array_example = np.array([[[0, 1, 2, 3],
                               [4, 5, 6, 7]],

                            [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                            [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

In [16]:
array_example.ndim

3

In [17]:
array_example.size

24

In [18]:
array_example.shape

(3, 2, 4)

##### Indexing and slicing

In [20]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [21]:
print(a[a < 5])

[1 2 3 4]


In [22]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [23]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [24]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


##### Create an array from existing data

In [26]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr1 = a[2:6]
arr1

array([3, 4, 5, 6])

##### Array Operations

In [30]:
data = np.array([1,2])

In [31]:
ones = np.ones(2, dtype = int)

In [32]:
data + ones

array([2, 3])

In [34]:
data * ones

array([1, 2])

In [35]:
data - ones

array([0, 1])