# From the NumPy documentation

https://numpy.org/doc/stable/user/quickstart.html
***

In [21]:
import numpy as np

In [9]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
x = np.arange(0, 50, .5)

In [16]:
x.dtype

dtype('float64')

In [20]:
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [22]:
x.shape

(100,)

In [17]:
y = np.arange(0, 25, .25)

In [18]:
y.dtype

dtype('float64')

In [19]:
y

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,
        4.5 ,  4.75,  5.  ,  5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,
        6.75,  7.  ,  7.25,  7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,
        9.  ,  9.25,  9.5 ,  9.75, 10.  , 10.25, 10.5 , 10.75, 11.  ,
       11.25, 11.5 , 11.75, 12.  , 12.25, 12.5 , 12.75, 13.  , 13.25,
       13.5 , 13.75, 14.  , 14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 ,
       15.75, 16.  , 16.25, 16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75,
       18.  , 18.25, 18.5 , 18.75, 19.  , 19.25, 19.5 , 19.75, 20.  ,
       20.25, 20.5 , 20.75, 21.  , 21.25, 21.5 , 21.75, 22.  , 22.25,
       22.5 , 22.75, 23.  , 23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 ,
       24.75])

In [35]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [24]:
y.shape

(100,)

In [50]:
y.reshape(-1,10)

array([[0.0000e+00, 2.5000e-01, 1.0000e+00, 2.2500e+00, 4.0000e+00,
        6.2500e+00, 9.0000e+00, 1.2250e+01, 1.6000e+01, 2.0250e+01],
       [2.5000e+01, 3.0250e+01, 3.6000e+01, 4.2250e+01, 4.9000e+01,
        5.6250e+01, 6.4000e+01, 7.2250e+01, 8.1000e+01, 9.0250e+01],
       [1.0000e+02, 1.1025e+02, 1.2100e+02, 1.3225e+02, 1.4400e+02,
        1.5625e+02, 1.6900e+02, 1.8225e+02, 1.9600e+02, 2.1025e+02],
       [2.2500e+02, 2.4025e+02, 2.5600e+02, 2.7225e+02, 2.8900e+02,
        3.0625e+02, 3.2400e+02, 3.4225e+02, 3.6100e+02, 3.8025e+02]])

In [48]:
x = np.arange(0.0, 21.0, 0.5)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [44]:
y = x ** 2
y

array([0.0000e+00, 2.5000e-01, 1.0000e+00, 2.2500e+00, 4.0000e+00,
       6.2500e+00, 9.0000e+00, 1.2250e+01, 1.6000e+01, 2.0250e+01,
       2.5000e+01, 3.0250e+01, 3.6000e+01, 4.2250e+01, 4.9000e+01,
       5.6250e+01, 6.4000e+01, 7.2250e+01, 8.1000e+01, 9.0250e+01,
       1.0000e+02, 1.1025e+02, 1.2100e+02, 1.3225e+02, 1.4400e+02,
       1.5625e+02, 1.6900e+02, 1.8225e+02, 1.9600e+02, 2.1025e+02,
       2.2500e+02, 2.4025e+02, 2.5600e+02, 2.7225e+02, 2.8900e+02,
       3.0625e+02, 3.2400e+02, 3.4225e+02, 3.6100e+02, 3.8025e+02])

In [47]:
np.linspace(0.0, 5, 101)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 ,
       1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05, 2.1 , 2.15,
       2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 , 2.65, 2.7 ,
       2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  , 3.05, 3.1 , 3.15, 3.2 , 3.25,
       3.3 , 3.35, 3.4 , 3.45, 3.5 , 3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 ,
       3.85, 3.9 , 3.95, 4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35,
       4.4 , 4.45, 4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 ,
       4.95, 5.  ])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
i.dtype

dtype('float64')

In [60]:
i.astype('int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [61]:
i[2]

array([0., 0., 1.])

# End
***